

export const Admin_Action_Types = {
    ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",

    ADMIN_LOGOUT: "ADMIN_LOGOUT",


    SHOW_ALL_USER_REQUEST: "SHOW_ALL_USER_REQUEST",
    SHOW_ALL_USER_SUCCESS: "SHOW_ALL_USER_SUCCESS",
    SHOW_ALL_USER_FAIL: "SHOW_ALL_USER_FAIL",

    ADMIN_USERBLOCKUNBLOCK_REQUEST: "ADMIN_USERBLOCKUNBLOCK_REQUEST",
    ADMIN_USERBLOCKUNBLOCK_SUCCESS: "ADMIN_USERBLOCKUNBLOCK_SUCCESS",
    ADMIN_USERBLOCKUNBLOCK_FAIL: "ADMIN_USERBLOCKUNBLOCK_FAIL",

    ADMIN_ADDVEHICLE_REQUEST: "ADMIN_ADDVEHICLE_REQUEST",
    ADMIN_ADDVEHICLE_SUCCESS: "ADMIN_ADDVEHICLE_SUCCESS",
    ADMIN_ADDVEHICLE_FAIL: "ADMIN_ADDVEHICLE_FAIL",

    DELETE_VEHICLE_REQUEST:"DELETE_VEHICLE_REQUEST",
    DELETE_VEHICLE_SUCCESS:"DELETE_VEHICLE_SUCCESS",
    DELETE_VEHICLE_FAIL:"DELETE_VEHICLE_FAIL",

    UPDATE_VEHICLE_REQUEST :"UPDATE_VEHICLE_REQUEST",
    UPDATE_VEHICLE_SUCCESS :"UPDATE_VEHICLE_SUCCESS",
    UPDATE_VEHICLE_FAIL :"UPDATE_VEHICLE_FAIL",

    
    SHOW_ALL_VEHICLE_REQUEST: "SHOW_ALL_VEHICLE_REQUEST",
    SHOW_ALL_VEHICLE_SUCCESS: "SHOW_ALL_VEHICLE_SUCCESS",
    SHOW_ALL_VEHICLE_FAIL: "SHOW_ALL_VEHICLE_FAIL",

    
    SHOW_USER_VEHICLE_SUCCESS: "SHOW_USER_VEHICLE_SUCCESS",
    SHOW_USER_VEHICLE_REQUEST: "SHOW_USER_VEHICLE_REQUEST",
    SHOW_USER_VEHICLE_FAIL: "SHOW_USER_VEHICLE_FAIL",

    USER_VEHICLE_ACCEPT_REQUEST:"USER_VEHICLE_ACCEPT_REQUEST",
    USER_VEHICLE_ACCEPT_SUCCESS:"USER_VEHICLE_ACCEPT_SUCCESS",
    USER_VEHICLE_ACCEPT_FAIL:"USER_VEHICLE_ACCEPT_FAIL",

    USER_VEHICLE_REJECT_REQUEST:"USER_VEHICLE_REJECT_REQUEST",
    USER_VEHICLE_REJECT_SUCCESS:"USER_VEHICLE_REJECT_SUCCESS",
    USER_VEHICLE_REJECT_FAIL:"USER_VEHICLE_REJECT_FAIL",

    ADD_COUPON_REQUEST:"ADD_COUPON_REQUEST",
    ADD_COUPON_SUCCESS:"ADD_COUPON_SUCCESS",
    ADD_COUPON_FAIL:"ADD_COUPON_FAIL",

    GET_BOOKING_DETAILS_REQUEST:"GET_BOOKING_DETAILS_REQUEST",
    GET_BOOKING_DETAILS_SUCCESS:"GET_BOOKING_DETAILS_SUCCESS",
    GET_BOOKING_DETAILS_FAIL:"GET_BOOKING_DETAILS_FAIL",



}