

export const Admin_Action_Types = {
    ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",

    ADMIN_LOGOUT: "ADMIN_LOGOUT",


    SHOW_ALL_USER_REQUEST: "SHOW_ALL_USER_REQUEST",
    SHOW_ALL_USER_SUCCESS: "SHOW_ALL_USER_SUCCESS",
    SHOW_ALL_USER_FAIL: "SHOW_ALL_USER_FAIL",

    ADMIN_USERBLOCKUNBLOCK_REQUEST: "ADMIN_USERBLOCKUNBLOCK_REQUEST",
    ADMIN_USERBLOCKUNBLOCK_SUCCESS: "ADMIN_USERBLOCKUNBLOCK_SUCCESS",
    ADMIN_USERBLOCKUNBLOCK_FAIL: "ADMIN_USERBLOCKUNBLOCK_FAIL",

    ADMIN_ADDVEHICLE_REQUEST: "ADMIN_ADDVEHICLE_REQUEST",
    ADMIN_ADDVEHICLE_SUCCESS: "ADMIN_ADDVEHICLE_SUCCESS",
    ADMIN_ADDVEHICLE_FAIL: "ADMIN_ADDVEHICLE_FAIL",

    SHOW_ALL_VEHICLE_REQUEST: "SHOW_ALL_VEHICLE_REQUEST",
    SHOW_ALL_VEHICLE_SUCCESS: "SHOW_ALL_VEHICLE_SUCCESS",
    SHOW_ALL_VEHICLE_FAIL: "SHOW_ALL_VEHICLE_FAIL",



}