

export const Admin_Action_Types = {
    ADMIN_LOGIN_REQUEST: "ADMIN_LOGIN_REQUEST",
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",

    SHOW_ALL_USER_REQUEST: "SHOW_ALL_USER_REQUEST",
    SHOW_ALL_USER_SUCCESS: "SHOW_ALL_USER_SUCCESS",
    SHOW_ALL_USER_FAIL: "SHOW_ALL_USER_FAIL",

    ADMIN_USERBLOCKUNBLOCK_REQUEST: "ADMIN_USERBLOCKUNBLOCK_REQUEST",
    ADMIN_USERBLOCKUNBLOCK_SUCCESS: "ADMIN_USERBLOCKUNBLOCK_SUCCESS",
    ADMIN_USERBLOCKUNBLOCK_FAIL: "ADMIN_USERBLOCKUNBLOCK_FAIL",

}