export const User_Action_Types = {
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",

  GOOGLE_SIGNUP_REQ: "GOOGLE_SIGNUP_REQ",
  GOOGLE_SIGNUP_SUCCESS: "GOOGLE_SIGNUP_SUCCESS",
  GOOGLE_SIGNUP_FAILED: "GOOGLE_SIGNUP_FAILED",

  LOGIN_WITH_OTP_REQUEST:"LOGIN_WITH_OTP_REQUEST",
  LOGIN_WITH_OTP_SUCCESS:"LOGIN_WITH_OTP_SUCCESS",
  LOGIN_WITH_OTP_FAIL:"LOGIN_WITH_OTP_FAIL",


  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",

  UPLOAD_PROFILE_REQUEST: " UPLOAD_PROFILE_REQUEST",
  UPLOAD_PROFILE_SUCCESS: " UPLOAD_PROFILE_SUCCESS",
  UPLOAD_PROFILE_FAIL: " UPLOAD_PROFILE_FAIL",

  EDIT_USER_REQUEST: "EDIT_USER_REQUEST",
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  GET_ALL_VEHICLE_REQUEST :"GET_ALL_VEHICLE_REQUEST",
  GET_ALL_VEHICLE_SUCCESS :"GET_ALL_VEHICLE_SUCCESS",
  GET_ALL_VEHICLE_FAIL :"GET_ALL_VEHICLE_FAIL",

};
